### ISSUE TITLE
Read Me - youtube link isn't working. 

### ISSUE THREAD

**Issue by sanjaypradeep** [pylenin/Python30#4]
ended up opening in a new tab, here's the url found in my address bar. 

<img width="1242" alt="Screen Shot 2019-06-11 at 12 11 36 AM" src="https://user-images.githubusercontent.com/18122757/59218347-b0196b80-8bdd-11e9-9068-26ac84c67b99.png">
https://www.youtube.com/watch?v=qk7qqbZxJGo&feature=youtu.be

**Comment by pylenin** [comment]
Are you accessing Day 3? It is set to private now. Had plans of releasing it tomorrow at 6.30 AM. Sorry about that.

**Comment by pylenin** [comment]
<img width="409" alt="Screen Shot 2019-06-10 at 8 44 59 PM" src="https://user-images.githubusercontent.com/44732615/59218475-a7ff0300-8bc0-11e9-8000-7ddc205df451.png">

**Comment by pylenin** [comment]
Feel free to close the issue once you are done !! Thanks for being proactive.

**Comment by sanjaypradeep** [comment]
Thanks for your comment. haha I was kinda worried that I'm a day behind. No problem, once it's getting open, let me close this issue.

**Comment by sanjaypradeep** [comment]
It's working now!
