### ISSUE TITLE
(Python3 Date) URL mentioned in "Description" below Youtube Video isn't the correct URL.

### ISSUE THREAD

**Issue by sanjaypradeep** [pylenin/Python30#6]
<img width="1311" alt="URL issue" src="https://user-images.githubusercontent.com/18122757/59294569-609b7400-8c9f-11e9-8bbd-925cca3790fe.png">

**Comment by pylenin** [comment]
Updated !! Turns out Youtube doesn't allow links bigger than certain characters.
